### ISSUE TITLE
Loading the 36c3 section yields "Error updating Events for 36c3"

### ISSUE THREAD

**Issue by gverilla** [NiciDieNase/chaosflix#44] opened 2019-12-29 18:57 UTC
This error occurs reproducibly, every time on my Pixel 3aXL, Android 10. Tested with most recent PlayStore- and the last Github-release, same thing happens for either version.

Relevant messages turning up in logcat: 
[logcat_12-29-2019_19-52-23.txt](https://github.com/NiciDieNase/chaosflix/files/4008432/logcat_12-29-2019_19-52-23.txt)

**Comment by NiciDieNase** [comment] 2020-01-02 11:54
This error was caused by unexpected null values from the api, should be fixed with version 0.5.4.
(Playstore and app itself still say 0.5.3 because I forgot to update the version, but it's the current version on play store and tagged as 0.5.4 on github)

**Closed as completed by NiciDieNase** 2020-01-02 11:54 UTC
Labels: bug
