### ISSUE TITLE
Fdroid support

### ISSUE THREAD

**Issue by theScrabi** [NiciDieNase/chaosflix#26] opened 2018-01-02 18:17 UTC
Please submit your app to [fdroid](https://f-droid.org). :)

However you may need to ensure not to introduce any nonfree libraries like google play services to the app :)

When i have a computer with again me I'll help u.

Rgds schabi

**Comment by NiciDieNase** [comment] 2018-01-02 18:48
Duplicate of #18

**Closed as completed** 2018-01-02 21:10 UTC
